services:
  - type: wserv
    repo: https://github.com/BrunoSobrino/TheMystic-Bot-MD
    name: TheMystic-Bot-MD
    env: node
    plan: free
    buildCommand: yarn
    startCommand: node index.js
    envVars:
      - key: UPSTREAM
        fromService:
          name: private-service
          type: pserv
          property: hostport
      - key: OAUTH2_PROXY_PROVIDER
        sync: false
      - key: OAUTH2_PROXY_CLIENT_ID
        sync: false
      - key: OAUTH2_PROXY_CLIENT_SECRET
        sync: false
      - key: OAUTH2_PROXY_COOKIE_SECRET
        generateValue: true
      - key: OAUTH2_PROXY_EMAIL_DOMAINS
        value: '*'
      - key: OAUTH2_PROXY_HTTP_ADDRESS
        value: ":10000"
